<h1 style='color:blue'>Assignments related to NumPy</h1>

In [2]:
import numpy as np
import matplotlib.pyplot as plt

<h2 style='color:red'>Creating Array</h2>

#### Create an array of 10 elements with values 10 to 1

In [3]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### Create an array of 3 X 3 filled with value 10

In [4]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

#### Create an array of 20 elements with random numbers between 50 and 100

In [5]:
np.random.randint(50,100,20)

array([82, 89, 59, 75, 91, 70, 63, 89, 50, 94, 71, 61, 80, 98, 99, 74, 50,
       87, 53, 99])

#### Create an array of 10 elements with values between 1 to 25 with uniform interval

In [6]:
np.linspace(1,25,10)

array([ 1.        ,  3.66666667,  6.33333333,  9.        , 11.66666667,
       14.33333333, 17.        , 19.66666667, 22.33333333, 25.        ])

<h2 style='color:red'>Indexing and Slicing </h2>

In [7]:
ar = np.random.randint(1,100,(5,5))
ar

array([[11,  9, 83,  2, 87],
       [35, 71, 12, 48, 94],
       [51,  9, 11,  1, 31],
       [96, 53, 45, 24, 97],
       [95, 31, 16, 55, 16]])

#### Display last 2 rows of a 5,5 array 

In [8]:
ar[-2:,:]

array([[96, 53, 45, 24, 97],
       [95, 31, 16, 55, 16]])

#### Display last 2 columns of 3rd to 5th rows 

In [9]:
ar[2:5,-2:]

array([[ 1, 31],
       [24, 97],
       [55, 16]])

#### Display last column of all alternate rows 

In [15]:
ar[::2,-1:] # This will produce a Matrix (3x1)

array([[87],
       [31],
       [16]])

In [16]:
ar[::2,-1]  # This will give a Vector

array([87, 31, 16])

#### Display rows 0,3,4 and columns 1,3 of 5,5 array

In [30]:
ridx = [0,3,4]
cidx = [1,3]
ar[ridx,1::2]

array([[44, 69],
       [77, 26],
       [13, 54]])

#### Display all elements where number is even

In [33]:
print(ar[ar%2==0])

[44 34 48 20 82 82 38 26 38 54 46]


<h2 style='color:red'>Array Operations </h2>

#### Add 1 to all even numbers in the array

In [34]:
even_idx = ar % 2 == 0
ar[even_idx] = ar[even_idx] + 1
ar

array([[25, 45, 23, 69, 35],
       [65, 97, 49, 21, 83],
       [73, 83, 41, 89, 39],
       [35, 77, 73, 27, 27],
       [65, 13, 39, 55, 47]])

#### Store square of all elements in the array 

In [73]:
a = np.random.randint(1,30,10)
print(a)
a_squares = a * a
print(a_squares)

[26 19  1 17 28 12 22  5  5 19]
[676 361   1 289 784 144 484  25  25 361]


<h2 style="color:red">Methods of ndarray</h2>

#### Display cumulative sum of elements in array of 10 elements 

In [74]:
a.cumsum()

array([ 26,  45,  46,  63,  91, 103, 125, 130, 135, 154], dtype=int32)

#### Display where in a sorted array of 10 elements number 20 fits in

In [75]:
a.sort() # Sorts in place
a.searchsorted(20)

7

#### Display index for maximum and minimum value in an array of 10 elements 

In [2]:
b = np.random.randint(1,10,10)
print(b)
np.where(b==b.max())

[4 5 4 7 6 9 8 8 5 1]


(array([5], dtype=int64),)

In [5]:
# Another way
b.tolist().index(b.max())

5

#### Display highest value in each row in 5,5 array 

In [84]:
a = np.random.randint(1,50,(5,5))
print(a)
max_avg = a.max(axis=1)
print("Highest value in each row = ", max_avg)

[[14 17  1 41 20]
 [11 45 38 31 40]
 [22 25 36 29  2]
 [37 36 44 27 45]
 [41  7  7  1 24]]
Highest value in each row =  [41 45 36 45 41]


#### Display average of each row 

In [85]:
avg = a.mean(axis=1)
print("Average of each row = ", avg)

Average of each row =  [18.6 33.  22.8 37.8 16. ]


#### Display all non-zero elements of a 5,5 array

In [86]:
a = np.random.randint(0,5,(5,5))
print(a)
a[a != 0]

[[4 0 3 0 0]
 [2 2 3 4 0]
 [0 4 1 3 3]
 [2 3 1 2 0]
 [4 1 2 0 2]]


array([4, 3, 2, 2, 3, 4, 4, 1, 3, 3, 2, 3, 1, 2, 4, 1, 2, 2])

#### Sort each row of a 5,5 array

In [88]:
a.sort(axis=1)
a

array([[0, 0, 0, 3, 4],
       [0, 2, 2, 3, 4],
       [0, 1, 3, 3, 4],
       [0, 1, 2, 2, 3],
       [0, 1, 2, 2, 4]])

<h2 style="color:red">Reshaping, stacking and splitting an Array</h2>

#### Reshape an array of 2,6 to 3,4 

In [95]:
a = np.random.randint(1,10,(2,6))
print(a)
a.reshape((3,4))

[[7 5 3 3 3 5]
 [9 9 3 2 7 8]]


array([[7, 5, 3, 3],
       [3, 5, 9, 9],
       [3, 2, 7, 8]])

#### Convert a 3,3 array to a single dimension array and create a copy

In [97]:
a = np.random.randint(1,10,(3,3))
print(a)
b = a.flatten()
b

[[7 3 1]
 [9 4 1]
 [9 7 7]]


array([7, 3, 1, 9, 4, 1, 9, 7, 7])

#### Reshape an array of 2,6 to 3,4 inplace

In [99]:
a = np.random.randint(1,10,(2,6))
print(a)
a.resize((3,4))
a

[[7 1 6 4 7 2]
 [8 5 2 1 3 5]]


array([[7, 1, 6, 4],
       [7, 2, 8, 5],
       [2, 1, 3, 5]])

#### Create an array of 5,5 and transpose it 


In [100]:
a = np.random.randint(1,25,(5,5))
print(a)
a.T

[[10 18  2 18 18]
 [13 22 20 16 15]
 [ 8 16 22 24 18]
 [ 1  6 11 23 10]
 [20  2  8 15  3]]


array([[10, 13,  8,  1, 20],
       [18, 22, 16,  6,  2],
       [ 2, 20, 22, 11,  8],
       [18, 16, 24, 23, 15],
       [18, 15, 18, 10,  3]])

#### Split an array of 5,5 into three parts at 2nd and 4th rows 

In [104]:
np.vsplit(a,(2,4))

[array([[10, 18,  2, 18, 18],
        [13, 22, 20, 16, 15]]), array([[ 8, 16, 22, 24, 18],
        [ 1,  6, 11, 23, 10]]), array([[20,  2,  8, 15,  3]])]

#### Concatenate two arrays of 3,3 and 4,3 into one array

In [105]:
a = np.random.randint(1,20,(3,3))
print(a)
b = np.random.randint(1,20,(4,3))
print(b)
np.vstack((a,b))

[[ 3  5 17]
 [12  8 14]
 [ 1 15  6]]
[[11 16  3]
 [19  9 13]
 [ 8  2 12]
 [12 16  2]]


array([[ 3,  5, 17],
       [12,  8, 14],
       [ 1, 15,  6],
       [11, 16,  3],
       [19,  9, 13],
       [ 8,  2, 12],
       [12, 16,  2]])

#### Split an array of 6,6 into two parts horizontally

In [107]:
a = np.random.randint(10,50,(6,6))
print(a)
np.hsplit(a,2)

[[30 47 32 41 23 15]
 [11 48 37 22 21 14]
 [25 16 29 11 23 21]
 [20 22 47 23 12 14]
 [46 34 21 46 12 30]
 [22 48 28 12 31 11]]


[array([[30, 47, 32],
        [11, 48, 37],
        [25, 16, 29],
        [20, 22, 47],
        [46, 34, 21],
        [22, 48, 28]]), array([[41, 23, 15],
        [22, 21, 14],
        [11, 23, 21],
        [23, 12, 14],
        [46, 12, 30],
        [12, 31, 11]])]