In [51]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

In [52]:
# Input data - SQFT, BED Rooms, Age in Years
X = np.array([
    [1000, 2, 10],
    [1500, 3, 5],
    [800, 2, 20],
    [2000, 4, 2]
], dtype=float)

y = np.array([2000000, 3000000, 1500000, 4000000], dtype=float)

In [53]:
X.max(axis=0)

array([2000.,    4.,   20.])

In [54]:
# Normalize data (important for neural networks)
X_max = X.max(axis=0)
y_max = y.max()

X = X / X_max
y = y / y_max

In [55]:
X

array([[0.5 , 0.5 , 0.5 ],
       [0.75, 0.75, 0.25],
       [0.4 , 0.5 , 1.  ],
       [1.  , 1.  , 0.1 ]])

In [56]:
# Build model
model = keras.Sequential([
    keras.Input(shape=(3,)),
    layers.Dense(2, activation='relu', ),  
    layers.Dense(1, activation='linear')    # Output layer
])

In [57]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                      │ (None, 2)                   │               8 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 11 (44.00 B)

 Trainable params: 11 (44.00 B)

 Non-trainable params: 0 (0.00 B)

In [58]:
# Compile
model.compile(optimizer='adam', loss='mse')

In [68]:
# Train
model.fit(X, y, epochs=50)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 4.7167
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 4.6855
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 4.6544
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 4.6236
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 4.5929
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 4.5625
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 4.5323
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 4.5024
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 4.4726
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 4.4430
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 4.4137
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 4.3845
Epoch 13/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 4.3556
Epoch 14/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 4.3268
Epoch 15/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 4.2983
Epoch 16/50
1/1 ━━━━━━━━━━━━━━━━━━

In [69]:
y_p = model.predict(X) * y_max

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


In [70]:
y_p

array([[-4007081.50863647],
       [-3971306.32400513],
       [-6340099.81155396],
       [-4432120.80001831]])

In [71]:
model.get_weights()

[array([[ 0.82261956, -0.15563868],
        [ 0.08928647,  0.7911155 ],
        [ 0.692478  ,  0.81581056]], dtype=float32),
 array([-0.08379725, -0.08439379], dtype=float32),
 array([[-0.64067507],
        [-0.97794825]], dtype=float32),
 array([0.08559643], dtype=float32)]

In [72]:
y_p[:,0] - (y * y_max)

array([-6007081.50863647, -6971306.32400513, -7840099.81155396,
       -8432120.80001831])

In [73]:
# Predict
test = np.array([[1200, 3, 8]])
test = test / X_max

In [74]:
prediction = model.predict(test)
print(prediction * y_max)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
[[-4491295.81451416]]
