In [38]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from keras.layers import Dense

In [39]:
# Load dataset
# Input -> Sepal Length, Sepal Width, Petal Length and Petal Width.
# Output -> Setosa, Versicolour, and Virginica
data = load_iris()
X = data.data
y = data.target

In [40]:
X.shape, y.shape

((150, 4), (150,))

In [41]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [42]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0
)

In [43]:
# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [52]:
# Build model (3 layers)
model = keras.Sequential([
    keras.Input(shape=(4,)), 
    Dense(4, activation='relu'),
    Dense(3, activation='relu'),
    Dense(3, activation='softmax')
])

In [53]:
# Compile
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [54]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                      │ (None, 4)                   │              20 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 3)                   │              15 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 3)                   │              12 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 47 (188.00 B)

 Trainable params: 47 (188.00 B)

 Non-trainable params: 0 (0.00 B)

In [47]:
model.get_weights()

[array([[-0.9391949 , -0.8203232 ],
        [ 0.47374964, -0.95618916],
        [-0.37956142,  0.9686723 ],
        [-0.3867271 , -0.75973725]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.03275335, -0.5428848 , -0.6972186 ],
        [-0.37055618,  0.91492486,  0.653188  ]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [48]:
# Train
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7083 - loss: 0.8386  
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7750 - loss: 0.8317 
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7750 - loss: 0.8253 
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7750 - loss: 0.8188 
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7833 - loss: 0.8127 
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7833 - loss: 0.8069 
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7833 - loss: 0.8008 
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7833 - loss: 0.7949 
Epoch 9/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7833 - loss: 0.7898 
Epoch 10/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7833 - loss: 0.7840 


In [49]:
model.get_weights()

[array([[-0.97775877, -0.78433144],
        [ 0.5110829 , -0.987128  ],
        [-0.41863152,  1.005758  ],
        [-0.42577147, -0.72282743]], dtype=float32),
 array([ 0.03895108, -0.00772223], dtype=float32),
 array([[ 0.00615041, -0.58157   , -0.7363831 ],
        [-0.3502142 ,  0.9313751 ,  0.6257347 ]], dtype=float32),
 array([-0.02439654, -0.02159565,  0.02986016], dtype=float32)]

In [50]:
# Evaluate
loss, acc = model.evaluate(X_test, y_test)
print("Test Accuracy:", acc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.7333 - loss: 0.7153
Test Accuracy: 0.7333333492279053


In [51]:
# Predict
predictions = model.predict(X_test[:5])
print("Predictions:\n", predictions)
print("Predicted classes:", np.argmax(predictions, axis=1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
Predictions:
 [[0.26124316 0.37576184 0.36299494]
 [0.03889652 0.62255853 0.338545  ]
 [0.77538085 0.13500208 0.08961707]
 [0.3269512  0.32786825 0.34518057]
 [0.7272484  0.15988824 0.11286329]]
Predicted classes: [1 1 0 2 0]
